### PR TITLE
Fix/text style issues

### LINKED ISSUE #1: The properties runTextStyle and mentionTextStyle should be dynamic
To avoid additional logic to update the MentionEditingController with styles based on theme (dark/light) or color scheme changes, properties for text styling should be in the widget tree

### PR DESCRIPTION
**Pull request by alex-melnyk**
resolves https://github.com/ApparyllisOrg/simply_mentions/issues/1

### CODE REVIEW

**Comment by alex-melnyk** [comment]
@Cellaryllis please review then we can update package

**Comment by Cellaryllis** [comment]
Thanks for the PR.

However, please don't add packages and your own lint style to the package. Keep the current style.

Implementation-wise, I must've misunderstood what you meant. Styling should still be modifiable per text field, removing it is a feature-removal. 

A solution that would permit both what you want and setting it per text style is by creating a custom MentionControllerThemeData class that would hold all the style properties, and this could then be passed into the controller. To suit your need, you would add a widget (MentionControllerTheme) that is like AppTheme/InheritedTheme that overrides the theme for children under that widget, then when it's time to use the text style it would try to access the values passed in the controller, and if it's null/invalid, use those from the theme.

Changes should also be reflected in the readme, so that the readme is not outdated.

**Comment by alex-melnyk** [comment]
> Thanks for the PR.
> 
> However, please don't add packages and your own lint style to the package. Keep the current style.
> 
> Implementation-wise, I must've misunderstood what you meant. Styling should still be modifiable per text field, removing it is a feature-removal.
> 
> A solution that would permit both what you want and setting it per text style is by creating a custom MentionControllerThemeData class that would hold all the style properties, and this could then be passed into the controller. To suit your need, you would add a widget (MentionControllerTheme) that is like AppTheme/InheritedTheme that overrides the theme for children under that widget, then when it's time to use the text style it would try to access the values passed in the controller, and if it's null/invalid, use those from the theme.
> 
> Changes should also be reflected in the readme, so that the readme is not outdated.

Thanks for the reply.

> However, please don't add packages and your own lint style to the package. Keep the current style.

You add no lints at all, even lint package, so I decided to add it.

> Implementation-wise, I must've misunderstood what you meant. Styling should still be modifiable per text field, removing it is a feature-removal.

First of all, by setting a single text style, you won't be able to change it, so every time the text style should be updated (e.g. user theme selection, device appearance changed, dark/light mode) you do need to dispose the previous controller object then create a new one, so my question is: why it is so complicated?

> A solution that would permit both what you want and setting it per text style is by creating a custom MentionControllerThemeData class that would hold all the style properties, and this could then be passed into the controller. To suit your need, you would add a widget (MentionControllerTheme) that is like AppTheme/InheritedTheme that overrides the theme for children under that widget, then when it's time to use the text style it would try to access the values passed in the controller, and if it's null/invalid, use those from the theme.

Additional nodes such as MentionControllerThemeData are useless because there is no custom theming or specific data that should be passed to the TextFileld widget. As per areas where theme should be changed, SDK has Theme widget made for this purpose. In other words, why should it be so complicated where only SDK component is used?!

> Changes should also be reflected in the readme, so that the readme is not outdated.

I agreed that readme should be updated. But in fact you don't wanna approve these changes, then I don't need to waste a time and continue to use fork with my changes in my project.

The biggest part of this PR is removing unnecessary typing for variables, code formatting, and fixing doc style instead of comment style ("//" vs "///"), keep in mind that is because you have no lint at all, so you can do a specific style not a STADARD

### Just to reference
I have been developing commercial applications since 2006. I started using Flutter in a commercial in 2020. I tried a lot of different lint rules, so I put lints that I'm using that is no so hard that it can be.

**Comment by Cellaryllis** [comment]
> You add no lints at all, even lint package, so I decided to add it.
> The biggest part of this PR is removing unnecessary typing for variables, code formatting, and fixing doc style instead of comment style ("//" vs "///"), keep in mind that is because you have no lint at all, so you are able to do a specific style not a STADARD

While I understand you think a lint should be added, and I don't disagree a lint should be added, but it shouldn't follow the lint style of your choosing without consultation whether this lint style is matching ours, we have internal packages or applications in dart/flutter that have lint, we just did not have time to add it to this one.

> First of all, by setting a single text style, you won't be able to change it, so every time the text style should be updated (e.g. user theme selection, device appearance changed, dark/light mode) you do need to dispose the previous controller object then create a new one, so my question is: why it is so complicated?
> Additional nodes such as MentionControllerThemeData are useless because there is no custom theming or specific data that should be passed to the TextFileld widget. As per areas where theme should be changed, SDK has Theme widget made for this purpose. In other words, why should it be so complicated where only SDK component is used?!

Okay, I see what you mean, though internally in our own applications we do use just this with a custom theme for app-specific-styling sitting at the top of the app that refreshes when dark/bright mode changes. But if you don't think that's a good solution because it wouldn't work without some custom handling of dark/bright theme, then perhaps instead of removing the style variables on the editing controller, make it optional, and if it's null/not set, use the AppTheme. Then you don't need to worry about making custom nodes, your current implementation from your current branch would not change, and we don't remove functionality that currently exists.

If you remove your lint changes so we can apply ours afterwards, and instead of removing the text style option from the controller all-together, you make it optional, we're happy to accept after reviewing the new code and testing it locally. 

> But in fact you don't wanna approve these changes, then I don't need to waste a time 
I have no issues accepting/approving your changes, if they don't remove existing functionality.

I am very willing to open a dialogue and talk about better ways how to do this, but this has to be civil. You're free to point out flaws in my reasoning with how we would solve the theming issue, but such dialogue should remain civil.

**Comment by alex-melnyk** [comment]
> > You add no lints at all, even lint package, so I decided to add it.
> > The biggest part of this PR is removing unnecessary typing for variables, code formatting, and fixing doc style instead of comment style ("//" vs "///"), keep in mind that is because you have no lint at all, so you are able to do a specific style not a STADARD
> 
> While I understand you think a lint should be added, and I don't disagree a lint should be added, but it shouldn't follow the lint style of your choosing without consultation whether this lint style is matching ours, we have internal packages or applications in dart/flutter that have lint, we just did not have time to add it to this one.
> 
> > First of all, by setting a single text style, you won't be able to change it, so every time the text style should be updated (e.g. user theme selection, device appearance changed, dark/light mode) you do need to dispose the previous controller object then create a new one, so my question is: why it is so complicated?
> > Additional nodes such as MentionControllerThemeData are useless because there is no custom theming or specific data that should be passed to the TextFileld widget. As per areas where theme should be changed, SDK has Theme widget made for this purpose. In other words, why should it be so complicated where only SDK component is used?!
> 
> Okay, I see what you mean, though internally in our own applications we do use just this with a custom theme for app-specific-styling sitting at the top of the app that refreshes when dark/bright mode changes. But if you don't think that's a good solution because it wouldn't work without some custom handling of dark/bright theme, then perhaps instead of removing the style variables on the editing controller, make it optional, and if it's null/not set, use the AppTheme. Then you don't need to worry about making custom nodes, your current implementation from your current branch would not change, and we don't remove functionality that currently exists.
> 
> If you remove your lint changes so we can apply ours afterwards, and instead of removing the text style option from the controller all-together, you make it optional, we're happy to accept after reviewing the new code and testing it locally.
> 
> > But in fact you don't wanna approve these changes, then I don't need to waste a time
> > I have no issues accepting/approving your changes, if they don't remove existing functionality.
> 
> I am very willing to open a dialogue and talk about better ways how to do this, but this has to be civil. You're free to point out flaws in my reasoning with how we would solve the theming issue, but such dialogue should remain civil.

Sorry for the pressure, I made changes.

Btw
> Okay, I see what you mean, though internally in our own applications we do use just this with a custom theme for app-specific-styling sitting at the top of the app that refreshes when dark/bright mode changes. But if you don't think that's a 

In the example app you can see:
- how easy avoid custom implementation on the theming switch dark/light
- properties mentionBgColor and mentionTextColor are useless
- if you comment out condition if (_mentionTextEditingController == null) { you will see that updated primary and onPrimary colors will pass through theme update automatically, because switching dark/light modes triggers widget tree update, exactly to update visual state of the widgets tree automatically.

**Comment by Cellaryllis** [comment]
Hey, thanks for the changes! We don't have time to look at it this weekend or next week, but we should have more time next weekend.

File: lib/text/mention_text_editing_controller.dart [hunk 1]
```diff
@@ -1,121 +1,76 @@
...
 
-  // Unique mention syntaxes, all syntaxes should have a different starting character
+  /// Unique mention syntaxes, all syntaxes should have a different
+  /// starting character
   final List<MentionSyntax> mentionSyntaxes;
 
-  // Delegate called when suggestion has changed
-  Function(MentionSyntax? syntax, String?)? onSugggestionChanged;
+  /// Delegate called when suggestion has changed
+  final SuggestionChangedCallback? onSuggestionChanged;
```
Comment (Cellaryllis) [inline lib/text/mention_text_editing_controller.dart]: This property was intentionally not final as we have use cases where we need to bind to the callback after the controller was created. Can you remove the final here? Once merged we'll then add final back, but instead use functions to add and remove listeners to this callback.

File: lib/text/mention_text_editing_controller.dart [hunk 2]
```diff
@@ -1,121 +1,76 @@
...
 
 import 'package:diff_match_patch/diff_match_patch.dart';
 import 'package:flutter/material.dart';
 
-// ignore_for_file: constant_identifier_names
-
-// Mention object that store the id, display name and avatarurl of the mention
-// You can inherit from this to add your own custom data, should you need to
-
-// Keep in copy with diff.dart from diff_match_patch package
```
Comment (Cellaryllis) [inline lib/text/mention_text_editing_controller.dart:11]: Keep this comment "Keep in copy with diff.dart from diff_match_patch package"

**Review by Cellaryllis — CHANGES_REQUESTED** [review]
Looks good, we tested it and it appears to be all working. 
Just two small comments, and then we're good to merge :) Thanks for the improvements!

File: lib/text/mention_text_editing_controller.dart (hunk 1 above)
Comment (alex-melnyk) [reply lib/text/mention_text_editing_controller.dart]: implemented listeners

File: lib/text/mention_text_editing_controller.dart (hunk 2 above)
Comment (alex-melnyk) [reply lib/text/mention_text_editing_controller.dart:11]: rolled back

**Comment by alex-melnyk** [comment]
@Cellaryllis while using package I faced with needs to:
- Make `idToMentionObject` async to await getting data from the database, so `setMarkupText` also became async
- Also based on request to implement listmers I added `MentionSuggestion` class  that holds mention syntax and search string

**Review by Cellaryllis — APPROVED** [review]

**Comment by Cellaryllis** [comment]
All merged, we'll prepare the release sometime today/tomorrow! Thanks for your help :)
